from pathlib import Path

APP_FILE = Path("app.py")
ACTIVE_MARKER = "# GOVERNANCE_ASSURANCE_PASSPORT_DETAIL_ACTIVE"
ANCHOR = '\nif __name__ == "__main__":'

route_code = r'''

# ============================================================
# GOVERNANCE_ASSURANCE_PASSPORT_DETAIL_ACTIVE
# Portable output layer generated by the Enterprise Assurance
# Passport Factory™. Does not overwrite the existing protected
# /governance-passport route.
# ============================================================

GOVERNANCE_ASSURANCE_PASSPORTS = {
    "BATCH-2026-041": {
        "object_type": "Manufacturing Batch",
        "domain": "Manufacturing Assurance",
        "owner": "Production + QA",
        "system_of_record": "Batch record / governed evidence chain",
        "assurance_score": 96,
        "passport_state": "CERTIFIED",
        "twin_state": "ALIGNED",
        "risk_state": "LOW",
        "primary_blocker": "None",
        "closure_verdict": "Issue certified passport",
        "summary": "Batch release evidence, approvals, integrity anchors, and closure conditions agree across the governed chain.",
        "why_it_matters": "This proves that release readiness is not a checklist opinion; it is backed by evidence, approval lineage, and integrity proof.",
        "controls": [
            "Batch release approval present",
            "Deviation review completed",
            "QA disposition recorded",
            "Evidence chain fingerprinted",
            "Final closure gate approved"
        ],
        "evidence_pack": [
            "Executed batch record",
            "QA release approval",
            "Deviation / exception review",
            "Evidence verification log",
            "Final release certificate"
        ],
        "integrity": {
            "hash": "Verified",
            "ledger": "Anchored",
            "lineage": "Continuous",
            "version": "Current"
        },
        "reconciliation": {
            "verdict": "ALIGNED",
            "detail": "Batch record, QA disposition, deviation review, and closure state agree."
        },
        "dependencies": [
            {"name": "QA approval", "state": "CLEARED"},
            {"name": "Deviation review", "state": "CLEARED"},
            {"name": "Evidence verification", "state": "CLEARED"}
        ],
        "exceptions": [
            {"name": "Open CAPA", "state": "NONE"},
            {"name": "Residual risk", "state": "NONE"}
        ],
        "dr_snapshot": {
            "tier": "Tier 2",
            "rto_rpo": "Recorded",
            "restore_proof": "Current",
            "restart_state": "Not applicable"
        },
        "dimensions": {
            "Control Coverage": 100,
            "Evidence Completeness": 100,
            "Integrity Anchoring": 100,
            "Reconciliation": 95,
            "Dependency Validation": 95,
            "Exception / CAPA Linkage": 95,
            "DR Readiness": 85,
            "Closure State": 100
        },
        "next_actions": [
            "Archive certified passport with batch release evidence.",
            "Use as inspection-ready release proof.",
            "Feed anonymized pattern into maturity scorecard."
        ]
    },
    "SOP-VAL-014": {
        "object_type": "SOP / Controlled Procedure",
        "domain": "SOP Governance",
        "owner": "Document Owner + QA",
        "system_of_record": "Controlled document repository",
        "assurance_score": 68,
        "passport_state": "CONDITIONAL",
        "twin_state": "DRIFT-SENSITIVE",
        "risk_state": "MEDIUM",
        "primary_blocker": "Operational practice drift",
        "closure_verdict": "Conditional passport only",
        "summary": "The approved SOP exists, but operational behavior no longer fully matches the controlled procedure.",
        "why_it_matters": "A document can be approved while real work has drifted. The passport should expose that difference rather than hide it.",
        "controls": [
            "Current SOP version approved",
            "Training matrix linked",
            "Comparison against field practice completed",
            "Gap severity classified",
            "Owner remediation path assigned"
        ],
        "evidence_pack": [
            "Approved SOP version",
            "Training completion extract",
            "SOP-to-reality comparison",
            "Gap severity report",
            "Remediation decision log"
        ],
        "integrity": {
            "hash": "Verified",
            "ledger": "Anchored",
            "lineage": "Continuous",
            "version": "Current"
        },
        "reconciliation": {
            "verdict": "CONTRADICTED",
            "detail": "Document control is green, but operational evidence shows practice drift against the approved workflow."
        },
        "dependencies": [
            {"name": "Training alignment", "state": "REVIEWABLE"},
            {"name": "Workflow remediation", "state": "OPEN"},
            {"name": "QA harmonization decision", "state": "OPEN"}
        ],
        "exceptions": [
            {"name": "SOP gap exception", "state": "OPEN"},
            {"name": "CAPA linkage", "state": "RECOMMENDED"}
        ],
        "dr_snapshot": {
            "tier": "Tier 3",
            "rto_rpo": "Not primary",
            "restore_proof": "Not primary",
            "restart_state": "Not applicable"
        },
        "dimensions": {
            "Control Coverage": 88,
            "Evidence Completeness": 80,
            "Integrity Anchoring": 100,
            "Reconciliation": 35,
            "Dependency Validation": 55,
            "Exception / CAPA Linkage": 65,
            "DR Readiness": 70,
            "Closure State": 50
        },
        "next_actions": [
            "Resolve SOP-to-reality drift before full certification.",
            "Route high-severity gaps into formal CAPA where required.",
            "Reissue passport after workflow and training evidence reconcile."
        ]
    },
    "CI-EQP-221": {
        "object_type": "CI / Regulated Asset",
        "domain": "CI Candidate Factory",
        "owner": "System Owner + IT Asset Custodian",
        "system_of_record": "ServiceNow / source asset records",
        "assurance_score": 78,
        "passport_state": "CONDITIONAL",
        "twin_state": "CROSS-SYSTEM",
        "risk_state": "MEDIUM",
        "primary_blocker": "Access-governance linkage",
        "closure_verdict": "Conditional passport pending IAM clearance",
        "summary": "The CI exists and the asset is identifiable, but ownership, MyAccess linkage, and user-role evidence are not yet fully reconciled.",
        "why_it_matters": "An asset can exist in the CMDB and still be governance-incomplete if access, ownership, and evidence are not connected.",
        "controls": [
            "Asset identity resolved",
            "Owner assigned",
            "CMDB candidate reviewed",
            "MyAccess relationship checked",
            "Duplicate risk evaluated"
        ],
        "evidence_pack": [
            "Asset source record",
            "CI candidate passport",
            "Owner review decision",
            "Access linkage evidence",
            "Duplicate reconciliation result"
        ],
        "integrity": {
            "hash": "Verified",
            "ledger": "Pending",
            "lineage": "Continuous",
            "version": "Current"
        },
        "reconciliation": {
            "verdict": "PARTIALLY ALIGNED",
            "detail": "Asset identity and owner agree, but access-governance linkage remains incomplete."
        },
        "dependencies": [
            {"name": "CMDB owner review", "state": "CLEARED"},
            {"name": "MyAccess mapping", "state": "OPEN"},
            {"name": "Duplicate check", "state": "CLEARED"}
        ],
        "exceptions": [
            {"name": "Unlinked privileged account", "state": "OPEN"},
            {"name": "CAPA linkage", "state": "NONE"}
        ],
        "dr_snapshot": {
            "tier": "Tier 2",
            "rto_rpo": "Assigned",
            "restore_proof": "Reviewable",
            "restart_state": "Not applicable"
        },
        "dimensions": {
            "Control Coverage": 85,
            "Evidence Completeness": 78,
            "Integrity Anchoring": 75,
            "Reconciliation": 72,
            "Dependency Validation": 60,
            "Exception / CAPA Linkage": 70,
            "DR Readiness": 80,
            "Closure State": 75
        },
        "next_actions": [
            "Clear MyAccess mapping before full certification.",
            "Confirm privileged-account owner and entitlement traceability.",
            "Reissue passport after IAM linkage closes."
        ]
    },
    "CSP-2026-009": {
        "object_type": "Sterile Compounding Record",
        "domain": "Compound Sterile AssuranceLayer™",
        "owner": "Pharmacy Supervisor + QA",
        "system_of_record": "Sterile compounding evidence chain",
        "assurance_score": 91,
        "passport_state": "CERTIFIED",
        "twin_state": "RELEASE-GATED",
        "risk_state": "LOW",
        "primary_blocker": "None",
        "closure_verdict": "Issue certified passport",
        "summary": "Personnel, environmental, batch, review, and custody evidence agree sufficiently for governed release.",
        "why_it_matters": "Sterile compounding safety depends on more than a single form; the passport proves the whole release chain.",
        "controls": [
            "Technician eligibility verified",
            "Environmental monitoring complete",
            "Batch evidence assembled",
            "Supervisor review approved",
            "Custody and seal lineage intact"
        ],
        "evidence_pack": [
            "Compounding batch record",
            "Environmental monitoring evidence",
            "Personnel qualification proof",
            "Supervisor review record",
            "Custody / seal health trace"
        ],
        "integrity": {
            "hash": "Verified",
            "ledger": "Anchored",
            "lineage": "Continuous",
            "version": "Current"
        },
        "reconciliation": {
            "verdict": "ALIGNED",
            "detail": "Batch, personnel, environmental, supervisor, and custody records agree."
        },
        "dependencies": [
            {"name": "Environmental monitoring", "state": "CLEARED"},
            {"name": "Supervisor review", "state": "CLEARED"},
            {"name": "Custody seal health", "state": "CLEARED"}
        ],
        "exceptions": [
            {"name": "Open deviation", "state": "NONE"},
            {"name": "Residual risk", "state": "NONE"}
        ],
        "dr_snapshot": {
            "tier": "Tier 2",
            "rto_rpo": "Recorded",
            "restore_proof": "Current",
            "restart_state": "Controlled"
        },
        "dimensions": {
            "Control Coverage": 95,
            "Evidence Completeness": 95,
            "Integrity Anchoring": 100,
            "Reconciliation": 95,
            "Dependency Validation": 92,
            "Exception / CAPA Linkage": 90,
            "DR Readiness": 82,
            "Closure State": 95
        },
        "next_actions": [
            "Archive certified release passport.",
            "Use as inspection-ready release proof.",
            "Feed anonymized chain into pharmacy maturity benchmarking."
        ]
    },
    "DR-2026-017": {
        "object_type": "DR Event",
        "domain": "Operational Recovery Governance",
        "owner": "System Owner + CSQA + BQA",
        "system_of_record": "Recovery governance chain",
        "assurance_score": 94,
        "passport_state": "CERTIFIED",
        "twin_state": "RECOVERY-GATED",
        "risk_state": "LOW",
        "primary_blocker": "None",
        "closure_verdict": "Issue certified recovery passport",
        "summary": "Activation, RTO/RPO outcome, dependency validation, evidence passport, restart approval, and certificate state all align.",
        "why_it_matters": "A system coming back online is not enough. The passport proves that the full recovery estate is defensible.",
        "controls": [
            "DR activation recorded",
            "RTO/RPO outcome captured",
            "Dependencies validated",
            "GMP restart gate approved",
            "Recovery certificate issued"
        ],
        "evidence_pack": [
            "Damage assessment report",
            "Backup restore log",
            "Data reconciliation matrix",
            "CSQA integrity verification",
            "BQA GMP impact assessment",
            "Recovery certificate"
        ],
        "integrity": {
            "hash": "Verified",
            "ledger": "Anchored",
            "lineage": "Continuous",
            "version": "Current"
        },
        "reconciliation": {
            "verdict": "ALIGNED",
            "detail": "Restore proof, QA verification, GMP restart, and closure certificate agree."
        },
        "dependencies": [
            {"name": "Data reconciliation", "state": "CLEARED"},
            {"name": "CSQA integrity verification", "state": "CLEARED"},
            {"name": "BQA impact assessment", "state": "CLEARED"},
            {"name": "Restart authority", "state": "CLEARED"}
        ],
        "exceptions": [
            {"name": "Residual recovery risk", "state": "RESOLVED"},
            {"name": "Root cause", "state": "CAPTURED"}
        ],
        "dr_snapshot": {
            "tier": "Tier 1",
            "rto_rpo": "Within threshold",
            "restore_proof": "Verified",
            "restart_state": "Approved"
        },
        "dimensions": {
            "Control Coverage": 100,
            "Evidence Completeness": 96,
            "Integrity Anchoring": 100,
            "Reconciliation": 95,
            "Dependency Validation": 95,
            "Exception / CAPA Linkage": 90,
            "DR Readiness": 100,
            "Closure State": 95
        },
        "next_actions": [
            "Archive recovery certificate package.",
            "Route lessons learned into resilience improvement.",
            "Use as DR audit-readiness proof."
        ]
    },
    "AR-NIAGARA-Q2": {
        "object_type": "Access Review",
        "domain": "Access Governance",
        "owner": "System Owner + IAM Reviewer",
        "system_of_record": "myAccess / controlled review evidence",
        "assurance_score": 82,
        "passport_state": "CONDITIONAL",
        "twin_state": "IAM-LINKED",
        "risk_state": "MEDIUM",
        "primary_blocker": "One privileged-account owner pending",
        "closure_verdict": "Conditional passport pending owner confirmation",
        "summary": "Quarterly access review is mostly complete, but one application-specific privileged account still lacks final owner confirmation.",
        "why_it_matters": "Access reviews are only defensible when entitlement, owner, training, and periodic-review evidence reconcile.",
        "controls": [
            "Review period defined",
            "System owner assigned",
            "Entitlement list checked",
            "Training reference linked",
            "Privileged accounts reconciled"
        ],
        "evidence_pack": [
            "Quarterly access review roster",
            "Owner approval record",
            "Privileged account inventory",
            "Training reference evidence",
            "Exception disposition log"
        ],
        "integrity": {
            "hash": "Verified",
            "ledger": "Pending",
            "lineage": "Continuous",
            "version": "Current"
        },
        "reconciliation": {
            "verdict": "PARTIALLY ALIGNED",
            "detail": "Standard access review is complete, but one privileged-account owner remains unresolved."
        },
        "dependencies": [
            {"name": "System owner review", "state": "CLEARED"},
            {"name": "Privileged-account owner", "state": "OPEN"},
            {"name": "Training linkage", "state": "CLEARED"}
        ],
        "exceptions": [
            {"name": "Privileged account exception", "state": "OPEN"},
            {"name": "CAPA linkage", "state": "NOT REQUIRED YET"}
        ],
        "dr_snapshot": {
            "tier": "Tier 3",
            "rto_rpo": "Not primary",
            "restore_proof": "Not primary",
            "restart_state": "Not applicable"
        },
        "dimensions": {
            "Control Coverage": 90,
            "Evidence Completeness": 85,
            "Integrity Anchoring": 75,
            "Reconciliation": 78,
            "Dependency Validation": 72,
            "Exception / CAPA Linkage": 75,
            "DR Readiness": 70,
            "Closure State": 80
        },
        "next_actions": [
            "Resolve privileged-account owner before certification.",
            "Update entitlement traceability once confirmed.",
            "Reissue passport after final review closure."
        ]
    },
    "CAPA-2026-032": {
        "object_type": "CAPA / Audit Finding",
        "domain": "Audit / CAPA Governance",
        "owner": "Quality Owner + Action Owner",
        "system_of_record": "CAPA register / evidence chain",
        "assurance_score": 57,
        "passport_state": "BLOCKED",
        "twin_state": "CLOSURE-GATED",
        "risk_state": "HIGH",
        "primary_blocker": "Effectiveness evidence missing",
        "closure_verdict": "Withhold passport",
        "summary": "The CAPA has a root cause and actions, but effectiveness evidence is still missing, so closure cannot be certified.",
        "why_it_matters": "A CAPA is not truly closed because actions were assigned; it is closed when effectiveness is proven.",
        "controls": [
            "Root cause defined",
            "Action owner assigned",
            "Due date tracked",
            "Effectiveness check required",
            "Closure approval gated"
        ],
        "evidence_pack": [
            "Audit finding",
            "Root cause analysis",
            "Corrective action plan",
            "Implementation proof",
            "Effectiveness evidence",
            "Closure approval"
        ],
        "integrity": {
            "hash": "Verified",
            "ledger": "Pending",
            "lineage": "Continuous",
            "version": "Current"
        },
        "reconciliation": {
            "verdict": "CONTRADICTED",
            "detail": "Action completion is recorded, but effectiveness proof needed for closure is missing."
        },
        "dependencies": [
            {"name": "Action implementation", "state": "CLEARED"},
            {"name": "Effectiveness check", "state": "OPEN"},
            {"name": "QA closure approval", "state": "BLOCKED"}
        ],
        "exceptions": [
            {"name": "Open effectiveness gap", "state": "OPEN"},
            {"name": "Residual risk", "state": "HIGH"}
        ],
        "dr_snapshot": {
            "tier": "Tier 3",
            "rto_rpo": "Not primary",
            "restore_proof": "Not primary",
            "restart_state": "Not applicable"
        },
        "dimensions": {
            "Control Coverage": 82,
            "Evidence Completeness": 45,
            "Integrity Anchoring": 75,
            "Reconciliation": 40,
            "Dependency Validation": 35,
            "Exception / CAPA Linkage": 60,
            "DR Readiness": 70,
            "Closure State": 20
        },
        "next_actions": [
            "Complete effectiveness testing before closure.",
            "Document risk disposition and QA review.",
            "Do not issue passport until closure gate passes."
        ]
    }
}


@app.route("/governance-assurance-passport/<object_id>")
def governance_assurance_passport_detail_view(object_id):
    normalized_id = str(object_id or "").upper().strip()
    profile = GOVERNANCE_ASSURANCE_PASSPORTS.get(normalized_id)

    if not profile:
        available_ids = list(GOVERNANCE_ASSURANCE_PASSPORTS.keys())
        return render_template_string("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Passport Not Found | COBIT-Chain™ / AssuranceLayer™</title>
    <style>
        body {
            margin:0;
            font-family:Arial,Helvetica,sans-serif;
            background:#f4f7fb;
            color:#172033;
        }
        .shell {
            max-width:900px;
            margin:0 auto;
            padding:42px 22px;
        }
        .card {
            background:#fff;
            border-radius:24px;
            padding:28px;
            box-shadow:0 10px 28px rgba(22,42,74,.08);
        }
        h1 { margin-top:0; }
        a {
            display:inline-block;
            margin-top:10px;
            text-decoration:none;
            background:#1d4ed8;
            color:#fff;
            padding:10px 14px;
            border-radius:999px;
            font-weight:800;
        }
        code {
            background:#eff6ff;
            padding:3px 6px;
            border-radius:8px;
        }
    </style>
</head>
<body>
    <div class="shell">
        <div class="card">
            <h1>Governance Assurance Passport™ not found</h1>
            <p>The requested object ID <code>{{ object_id }}</code> is not available in the current demo passport set.</p>
            <p><b>Available sample passports:</b></p>
            <ul>
                {% for item in available_ids %}
                <li>{{ item }}</li>
                {% endfor %}
            </ul>
            <a href="/enterprise-assurance-passport-factory">Return to Enterprise Assurance Passport Factory™</a>
        </div>
    </div>
</body>
</html>
        """, object_id=normalized_id, available_ids=available_ids), 404

    all_ids = list(GOVERNANCE_ASSURANCE_PASSPORTS.keys())
    dimensions = profile["dimensions"]
    sorted_dependencies = profile["dependencies"]
    sorted_exceptions = profile["exceptions"]

    return render_template_string("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Governance Assurance Passport™ | {{ object_id }}</title>
    <style>
        * { box-sizing:border-box; }
        body {
            margin:0;
            font-family:Arial,Helvetica,sans-serif;
            background:#f4f7fb;
            color:#172033;
        }
        .shell {
            max-width:1540px;
            margin:0 auto;
            padding:28px 22px 44px;
        }
        .topbar {
            display:flex;
            justify-content:space-between;
            align-items:center;
            gap:16px;
            flex-wrap:wrap;
            margin-bottom:22px;
        }
        .brand {
            font-size:14px;
            font-weight:900;
            color:#1d4ed8;
            letter-spacing:.06em;
            text-transform:uppercase;
        }
        .nav-links {
            display:flex;
            gap:10px;
            flex-wrap:wrap;
        }
        .nav-links a, .action-btn {
            text-decoration:none;
            color:#163a72;
            background:#e8f0ff;
            padding:9px 12px;
            border-radius:999px;
            font-size:13px;
            font-weight:800;
            border:0;
            cursor:pointer;
        }
        .hero {
            background:
                radial-gradient(circle at top right, rgba(34,197,94,.18), transparent 28%),
                linear-gradient(135deg,#071527 0%,#0f2745 42%,#1d4ed8 100%);
            color:#fff;
            border-radius:28px;
            padding:30px;
            box-shadow:0 18px 46px rgba(15,23,42,.24);
            margin-bottom:20px;
        }
        .eyebrow {
            font-size:13px;
            text-transform:uppercase;
            letter-spacing:.08em;
            opacity:.82;
            font-weight:800;
            margin-bottom:10px;
        }
        h1 {
            margin:0 0 10px;
            font-size:38px;
            line-height:1.12;
        }
        .hero p {
            max-width:1180px;
            margin:0;
            line-height:1.58;
            font-size:16px;
            opacity:.96;
        }
        .hero-grid {
            display:grid;
            grid-template-columns:repeat(6,minmax(0,1fr));
            gap:12px;
            margin-top:22px;
        }
        .hero-card {
            background:rgba(255,255,255,.12);
            border:1px solid rgba(255,255,255,.18);
            border-radius:18px;
            padding:15px;
        }
        .hero-label {
            font-size:12px;
            opacity:.80;
            text-transform:uppercase;
            letter-spacing:.06em;
            margin-bottom:7px;
        }
        .hero-value {
            font-size:21px;
            font-weight:900;
        }
        .hero-note {
            font-size:12px;
            opacity:.84;
            margin-top:5px;
            line-height:1.35;
        }
        .layout-2 {
            display:grid;
            grid-template-columns:1.05fr .95fr;
            gap:18px;
            margin-bottom:18px;
        }
        .grid-3 {
            display:grid;
            grid-template-columns:repeat(3,minmax(0,1fr));
            gap:16px;
            margin-bottom:18px;
        }
        .panel {
            background:#fff;
            border-radius:22px;
            padding:22px;
            box-shadow:0 10px 28px rgba(22,42,74,.08);
            margin-bottom:18px;
        }
        .panel h2 {
            margin:0 0 15px;
            font-size:21px;
        }
        .panel p {
            color:#44536b;
            line-height:1.56;
            margin:0 0 14px;
        }
        .passport-card {
            border:1px solid #bfdbfe;
            background:
                radial-gradient(circle at top right, rgba(59,130,246,.12), transparent 30%),
                linear-gradient(180deg,#ffffff 0%,#f8fbff 100%);
            border-radius:24px;
            padding:22px;
        }
        .passport-top {
            display:flex;
            justify-content:space-between;
            align-items:flex-start;
            gap:12px;
            flex-wrap:wrap;
            margin-bottom:16px;
        }
        .passport-kicker {
            font-size:12px;
            text-transform:uppercase;
            letter-spacing:.06em;
            color:#1d4ed8;
            font-weight:900;
            margin-bottom:7px;
        }
        .passport-title {
            font-size:27px;
            font-weight:900;
        }
        .seal {
            display:inline-block;
            border-radius:999px;
            padding:8px 12px;
            font-size:12px;
            font-weight:900;
            background:{% if profile.passport_state == "CERTIFIED" %}#dcfce7{% elif profile.passport_state == "CONDITIONAL" %}#fef3c7{% else %}#fee2e2{% endif %};
            color:{% if profile.passport_state == "CERTIFIED" %}#166534{% elif profile.passport_state == "CONDITIONAL" %}#92400e{% else %}#991b1b{% endif %};
        }
        .score-wrap {
            display:grid;
            grid-template-columns:150px 1fr;
            gap:18px;
            align-items:center;
        }
        .score-ring {
            width:132px;
            height:132px;
            border-radius:50%;
            background:conic-gradient(
                {% if profile.passport_state == "CERTIFIED" %}#16a34a{% elif profile.passport_state == "CONDITIONAL" %}#f59e0b{% else %}#dc2626{% endif %} 0deg,
                {% if profile.passport_state == "CERTIFIED" %}#16a34a{% elif profile.passport_state == "CONDITIONAL" %}#f59e0b{% else %}#dc2626{% endif %} {{ profile.assurance_score * 3.6 }}deg,
                #e5e7eb {{ profile.assurance_score * 3.6 }}deg,
                #e5e7eb 360deg
            );
            display:flex;
            align-items:center;
            justify-content:center;
            position:relative;
        }
        .score-ring::before {
            content:"";
            position:absolute;
            inset:15px;
            border-radius:50%;
            background:#fff;
        }
        .score-value {
            position:relative;
            z-index:1;
            font-size:32px;
            font-weight:900;
        }
        .verdict-box {
            border-radius:18px;
            padding:17px;
            background:{% if profile.passport_state == "CERTIFIED" %}#ecfdf5{% elif profile.passport_state == "CONDITIONAL" %}#fffbeb{% else %}#fef2f2{% endif %};
            border:1px solid {% if profile.passport_state == "CERTIFIED" %}#a7f3d0{% elif profile.passport_state == "CONDITIONAL" %}#fde68a{% else %}#fecaca{% endif %};
        }
        .verdict-label {
            font-size:11px;
            text-transform:uppercase;
            letter-spacing:.05em;
            color:#64748b;
            font-weight:900;
            margin-bottom:6px;
        }
        .verdict-title {
            font-size:24px;
            font-weight:900;
            color:{% if profile.passport_state == "CERTIFIED" %}#166534{% elif profile.passport_state == "CONDITIONAL" %}#92400e{% else %}#991b1b{% endif %};
            margin-bottom:7px;
        }
        .verdict-note {
            color:#475569;
            line-height:1.5;
        }
        .meta-grid {
            display:grid;
            grid-template-columns:repeat(4,minmax(0,1fr));
            gap:10px;
            margin-top:16px;
        }
        .meta-card {
            background:#fff;
            border:1px solid #e2eaf7;
            border-radius:14px;
            padding:12px;
        }
        .meta-label {
            font-size:11px;
            text-transform:uppercase;
            letter-spacing:.05em;
            color:#64748b;
            font-weight:900;
            margin-bottom:5px;
        }
        .meta-value {
            font-weight:900;
        }
        .dimension-grid {
            display:grid;
            gap:10px;
        }
        .dimension-row {
            display:grid;
            grid-template-columns:190px 1fr 70px;
            gap:10px;
            align-items:center;
        }
        .dimension-label {
            font-size:13px;
            font-weight:800;
        }
        .bar {
            height:12px;
            border-radius:999px;
            background:#e5e7eb;
            overflow:hidden;
        }
        .bar span {
            display:block;
            height:100%;
            border-radius:999px;
            background:linear-gradient(90deg,#2563eb,#16a34a);
        }
        .dimension-score {
            text-align:right;
            font-size:13px;
            font-weight:900;
        }
        .list-grid {
            display:grid;
            grid-template-columns:repeat(2,minmax(0,1fr));
            gap:14px;
        }
        .list-card {
            border:1px solid #e2eaf7;
            background:#f8fbff;
            border-radius:18px;
            padding:17px;
        }
        .list-card h3 {
            margin:0 0 10px;
            font-size:17px;
        }
        .list-card ul {
            margin:0;
            padding-left:20px;
            color:#475569;
            line-height:1.62;
        }
        .status-table {
            width:100%;
            border-collapse:collapse;
            border-radius:16px;
            overflow:hidden;
            font-size:13px;
        }
        .status-table th {
            background:#0f172a;
            color:#fff;
            text-align:left;
            padding:11px;
        }
        .status-table td {
            border-bottom:1px solid #e5e7eb;
            padding:11px;
            vertical-align:top;
        }
        .pill {
            display:inline-block;
            border-radius:999px;
            padding:6px 10px;
            font-size:12px;
            font-weight:900;
        }
        .pill.green { background:#dcfce7; color:#166534; }
        .pill.amber { background:#fef3c7; color:#92400e; }
        .pill.red { background:#fee2e2; color:#991b1b; }
        .pill.blue { background:#dbeafe; color:#1d4ed8; }
        .integrity-grid {
            display:grid;
            grid-template-columns:repeat(4,minmax(0,1fr));
            gap:12px;
        }
        .integrity-card {
            border:1px solid #e2eaf7;
            background:#f8fbff;
            border-radius:18px;
            padding:17px;
        }
        .integrity-label {
            font-size:12px;
            text-transform:uppercase;
            letter-spacing:.05em;
            color:#64748b;
            font-weight:900;
            margin-bottom:8px;
        }
        .integrity-value {
            font-size:18px;
            font-weight:900;
        }
        .story-card {
            border-left:7px solid #1d4ed8;
            background:linear-gradient(135deg,#eff6ff,#ffffff);
            border-radius:18px;
            padding:18px;
            line-height:1.62;
        }
        .selector-row {
            display:flex;
            flex-wrap:wrap;
            gap:10px;
        }
        .selector-row a {
            text-decoration:none;
            border:1px solid #dbeafe;
            background:#f8fbff;
            color:#1e3a8a;
            padding:9px 12px;
            border-radius:999px;
            font-size:13px;
            font-weight:800;
        }
        .selector-row a.active {
            background:#1d4ed8;
            color:#fff;
            border-color:#1d4ed8;
        }
        .next-actions {
            border-left:7px solid #16a34a;
            background:#ecfdf5;
            border-radius:18px;
            padding:18px;
        }
        .next-actions ul {
            margin:0;
            padding-left:20px;
            line-height:1.62;
            color:#475569;
        }
        .footer-note {
            color:#5c6a80;
            font-size:13px;
            line-height:1.55;
            margin-top:14px;
        }
        @media print {
            .topbar, .selector-panel, .action-row {
                display:none !important;
            }
            body {
                background:#fff;
            }
            .shell {
                max-width:none;
                padding:0;
            }
            .panel, .hero {
                box-shadow:none;
                break-inside:avoid;
            }
        }
        @media(max-width:1360px){
            .hero-grid {
                grid-template-columns:repeat(3,minmax(0,1fr));
            }
            .layout-2 {
                grid-template-columns:1fr;
            }
            .integrity-grid {
                grid-template-columns:repeat(2,minmax(0,1fr));
            }
        }
        @media(max-width:820px){
            .hero-grid,
            .meta-grid,
            .list-grid,
            .integrity-grid,
            .grid-3 {
                grid-template-columns:1fr;
            }
            .score-wrap {
                grid-template-columns:1fr;
            }
            .dimension-row {
                grid-template-columns:1fr;
            }
            h1 {
                font-size:29px;
            }
        }
    </style>
</head>
<body>
    <div class="shell">
        <div class="topbar">
            <div class="brand">COBIT-Chain™ / AssuranceLayer™</div>
            <div class="nav-links">
                <a href="/enterprise-assurance-passport-factory">Passport Factory</a>
                <a href="/command-center">Command Center</a>
                <a href="/modules">Modules Directory</a>
                <a href="/governance-digital-twin">Governance Digital Twin</a>
                <button class="action-btn" onclick="window.print()">Print / Save as PDF</button>
            </div>
        </div>

        <section class="hero">
            <div class="eyebrow">Portable Governance Output</div>
            <h1>Governance Assurance Passport™</h1>
            <p>
                A portable assurance record generated from the live Regulated Operations Assurance Twin™.
                This passport does not merely summarize a governed object; it records whether the full control,
                evidence, integrity, reconciliation, dependency, exception, recovery, and closure chain is defensible.
            </p>

            <div class="hero-grid">
                <div class="hero-card">
                    <div class="hero-label">Object ID</div>
                    <div class="hero-value">{{ object_id }}</div>
                    <div class="hero-note">{{ profile.object_type }}</div>
                </div>
                <div class="hero-card">
                    <div class="hero-label">Passport State</div>
                    <div class="hero-value">{{ profile.passport_state }}</div>
                    <div class="hero-note">{{ profile.closure_verdict }}</div>
                </div>
                <div class="hero-card">
                    <div class="hero-label">Assurance Score</div>
                    <div class="hero-value">{{ profile.assurance_score }}</div>
                    <div class="hero-note">Explainable composite</div>
                </div>
                <div class="hero-card">
                    <div class="hero-label">Twin State</div>
                    <div class="hero-value">{{ profile.twin_state }}</div>
                    <div class="hero-note">{{ profile.domain }}</div>
                </div>
                <div class="hero-card">
                    <div class="hero-label">Risk State</div>
                    <div class="hero-value">{{ profile.risk_state }}</div>
                    <div class="hero-note">Primary blocker: {{ profile.primary_blocker }}</div>
                </div>
                <div class="hero-card">
                    <div class="hero-label">Owner</div>
                    <div class="hero-value">{{ profile.owner }}</div>
                    <div class="hero-note">{{ profile.system_of_record }}</div>
                </div>
            </div>
        </section>

        <section class="panel selector-panel">
            <h2>Available Demo Passports</h2>
            <div class="selector-row">
                {% for item in all_ids %}
                <a href="/governance-assurance-passport/{{ item }}" class="{% if item == object_id %}active{% endif %}">
                    {{ item }}
                </a>
                {% endfor %}
            </div>
        </section>

        <section class="layout-2">
            <div class="panel">
                <h2>Passport Seal</h2>
                <div class="passport-card">
                    <div class="passport-top">
                        <div>
                            <div class="passport-kicker">Generated Passport</div>
                            <div class="passport-title">{{ profile.object_type }}</div>
                        </div>
                        <div class="seal">{{ profile.passport_state }}</div>
                    </div>

                    <div class="score-wrap">
                        <div class="score-ring">
                            <div class="score-value">{{ profile.assurance_score }}</div>
                        </div>

                        <div class="verdict-box">
                            <div class="verdict-label">Closure Verdict</div>
                            <div class="verdict-title">{{ profile.closure_verdict }}</div>
                            <div class="verdict-note">{{ profile.summary }}</div>
                        </div>
                    </div>

                    <div class="meta-grid">
                        <div class="meta-card">
                            <div class="meta-label">Domain</div>
                            <div class="meta-value">{{ profile.domain }}</div>
                        </div>
                        <div class="meta-card">
                            <div class="meta-label">Twin State</div>
                            <div class="meta-value">{{ profile.twin_state }}</div>
                        </div>
                        <div class="meta-card">
                            <div class="meta-label">Risk State</div>
                            <div class="meta-value">{{ profile.risk_state }}</div>
                        </div>
                        <div class="meta-card">
                            <div class="meta-label">Primary Blocker</div>
                            <div class="meta-value">{{ profile.primary_blocker }}</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel">
                <h2>Assurance Dimension Profile</h2>
                <div class="dimension-grid">
                    {% for label, score in dimensions.items() %}
                    <div class="dimension-row">
                        <div class="dimension-label">{{ label }}</div>
                        <div class="bar"><span style="width:{{ score }}%;"></span></div>
                        <div class="dimension-score">{{ score }}</div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>

        <section class="layout-2">
            <div class="panel">
                <h2>Control Coverage + Evidence Pack</h2>
                <div class="list-grid">
                    <div class="list-card">
                        <h3>Applied Controls</h3>
                        <ul>
                            {% for item in profile.controls %}
                            <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="list-card">
                        <h3>Required Evidence Pack</h3>
                        <ul>
                            {% for item in profile.evidence_pack %}
                            <li>{{ item }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="panel">
                <h2>Why This Passport Matters</h2>
                <div class="story-card">
                    <b>{{ profile.object_type }}:</b> {{ profile.why_it_matters }}
                </div>
            </div>
        </section>

        <section class="panel">
            <h2>Integrity Anchors</h2>
            <div class="integrity-grid">
                <div class="integrity-card">
                    <div class="integrity-label">Hash State</div>
                    <div class="integrity-value">{{ profile.integrity.hash }}</div>
                </div>
                <div class="integrity-card">
                    <div class="integrity-label">Ledger State</div>
                    <div class="integrity-value">{{ profile.integrity.ledger }}</div>
                </div>
                <div class="integrity-card">
                    <div class="integrity-label">Lineage State</div>
                    <div class="integrity-value">{{ profile.integrity.lineage }}</div>
                </div>
                <div class="integrity-card">
                    <div class="integrity-label">Version State</div>
                    <div class="integrity-value">{{ profile.integrity.version }}</div>
                </div>
            </div>
        </section>

        <section class="layout-2">
            <div class="panel">
                <h2>Cross-System Reconciliation Verdict</h2>
                <div class="story-card">
                    <b>{{ profile.reconciliation.verdict }}:</b> {{ profile.reconciliation.detail }}
                </div>
            </div>

            <div class="panel">
                <h2>DR / Continuity Snapshot</h2>
                <table class="status-table">
                    <tr><th>Field</th><th>State</th></tr>
                    <tr><td>Criticality Tier</td><td>{{ profile.dr_snapshot.tier }}</td></tr>
                    <tr><td>RTO / RPO</td><td>{{ profile.dr_snapshot.rto_rpo }}</td></tr>
                    <tr><td>Restore Proof</td><td>{{ profile.dr_snapshot.restore_proof }}</td></tr>
                    <tr><td>Restart State</td><td>{{ profile.dr_snapshot.restart_state }}</td></tr>
                </table>
            </div>
        </section>

        <section class="layout-2">
            <div class="panel">
                <h2>Dependency State</h2>
                <table class="status-table">
                    <tr><th>Dependency</th><th>State</th></tr>
                    {% for item in sorted_dependencies %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>
                            <span class="pill {% if item.state in ['CLEARED', 'RESOLVED', 'CAPTURED'] %}green{% elif item.state in ['REVIEWABLE', 'OPEN'] %}amber{% else %}red{% endif %}">
                                {{ item.state }}
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>

            <div class="panel">
                <h2>Exception / CAPA Linkage</h2>
                <table class="status-table">
                    <tr><th>Item</th><th>State</th></tr>
                    {% for item in sorted_exceptions %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>
                            <span class="pill {% if item.state in ['NONE', 'RESOLVED', 'CAPTURED'] %}green{% elif item.state in ['RECOMMENDED', 'NOT REQUIRED YET'] %}blue{% elif item.state in ['OPEN'] %}amber{% else %}red{% endif %}">
                                {{ item.state }}
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </section>

        <section class="panel">
            <h2>Recommended Next Actions</h2>
            <div class="next-actions">
                <ul>
                    {% for item in profile.next_actions %}
                    <li>{{ item }}</li>
                    {% endfor %}
                </ul>
            </div>
        </section>

        <section class="grid-3">
            <div class="panel">
                <h2>Portable</h2>
                <p>The same passport structure can travel across batches, SOPs, assets, sterile records, DR events, access reviews, and CAPA items.</p>
            </div>
            <div class="panel">
                <h2>Explainable</h2>
                <p>The score is not magic. It is backed by visible dimensions, evidence, dependencies, exceptions, and closure logic.</p>
            </div>
            <div class="panel">
                <h2>Audit-Ready</h2>
                <p>The passport can be printed or saved as PDF while preserving the assurance story that generated it.</p>
            </div>
        </section>

        <section class="panel">
            <h2>Strategic Meaning</h2>
            <p>
                The <b>Enterprise Assurance Passport Factory™</b> proves that COBIT-Chain™ can evaluate many regulated objects.
                The <b>Governance Assurance Passport™</b> proves what the platform produces:
                a portable, evidence-backed assurance record that is issued only when live governance truth supports it.
            </p>
            <div class="footer-note">
                This route is additive and does not replace the protected existing <b>/governance-passport</b> page.
            </div>
        </section>
    </div>
</body>
</html>
    """,
        object_id=normalized_id,
        profile=profile,
        all_ids=all_ids,
        dimensions=dimensions,
        sorted_dependencies=sorted_dependencies,
        sorted_exceptions=sorted_exceptions
    )
'''

def main():
    if not APP_FILE.exists():
        raise SystemExit("ERROR: app.py was not found in the current folder.")

    text = APP_FILE.read_text(encoding="utf-8")

    if ACTIVE_MARKER in text:
        print("SKIP: Governance Assurance Passport detail route already exists. No duplicate code inserted.")
        return

    if ANCHOR not in text:
        raise SystemExit('ERROR: Could not find anchor: if __name__ == "__main__":')

    updated = text.replace(ANCHOR, route_code + ANCHOR, 1)

    required_markers = [
        ACTIVE_MARKER,
        'GOVERNANCE_ASSURANCE_PASSPORTS = {',
        '@app.route("/governance-assurance-passport/<object_id>")',
        "Governance Assurance Passport™",
        "Passport Seal",
        "Assurance Dimension Profile",
        "Integrity Anchors",
        "Cross-System Reconciliation Verdict",
        "Recommended Next Actions",
    ]

    missing = [marker for marker in required_markers if marker not in updated]
    if missing:
        raise SystemExit(f"ERROR: Required markers missing after patch: {missing}")

    APP_FILE.write_text(updated, encoding="utf-8")
    print("SUCCESS: /governance-assurance-passport/<object_id> route inserted safely.")
    print("VERIFIED: required markers found and existing /governance-passport route not overwritten.")
    print("NEXT: run python -m py_compile app.py")

if __name__ == "__main__":
    main()
